
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqnejedmmwcumpqihupt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxbmVqZWRtbXdjdW1wcWlodXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTc1NjcsImV4cCI6MjA2MjczMzU2N30.Z4quCKDfD-Ry8uCxkmuExp5n5wxW_mjs9eccU1GJjyI";

// Export the URL for use in other parts of the application
export const SUPABASE_URL_ENDPOINT = SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
